const truthyOrFalsy = Boolean(3 >= 2);
// const truthyOrFalsy = Boolean(2 == "2");
// const truthyOrFalsy = Boolean(2 === "2");
// const truthyOrFalsy = Boolean(2 === 2);
// const truthyOrFalsy = Boolean("hello world");
// const truthyOrFalsy = Boolean("");
// const truthyOrFalsy = Boolean(0);
// const truthyOrFalsy = Boolean(50);
// const truthyOrFalsy = Boolean(5>1);
// const truthyOrFalsy = Boolean("1 > 10");
// const truthyOrFalsy = Boolean("false");
console.log("The expression is " + truthyOrFalsy);
